[database]
user = "postgres.elccunyrslwitjescdvn"           # ✅ From Supabase → "Connect" → Pooler
password = "kokorokoko123"     # ✅ From Supabase → Settings → Database → Reset password
host = "aws-0-ap-southeast-1.pooler.supabase.com"  # ✅ Pooler Host for IPv4
port = 6543                                       # ✅ Pooler Port
database = "postgres"                             # ✅ Default DB name
